name: Auto Fetch Nodes

on:
  workflow_dispatch:  # 保留手动触发
  schedule:
    - cron: '0 18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4 # 升级到 v4，彻底解决 Node.js 报错

    - name: Set up Python
      uses: actions/setup-python@v5 # 升级到 v5，适配最新环境
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install requests

    - name: Run Script
      run: python main.py

    - name: Commit and Push
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add sub/*
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update nodes" && git push)
